version: "3.4"

volumes:
  astro_node_modules:

services:
  database:
    container_name: database-server-dab-p1-227e211d-cbb0-49d2-a31c-bb8cca6b8282
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    profiles:
      - migrate

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  programming-api:
    build:
      context: programming-api
      dockerfile: Dockerfile.prod
    image: programming-api-prod
    restart: "on-failure"
    expose:
      - 7777
    depends_on:
      - database
      - redis
    env_file:
      - project.env
    deploy:
        replicas: 2
        restart_policy:
          condition: on-failure
          delay: "5s"
          max_attempts: 5
          window: "30s"

  grader-api:
    build:
      context: grader-api
      dockerfile: Dockerfile.prod
    image: grader-api-prod
    restart: "on-failure"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - database
      - redis
    env_file:
      - project.env
    deploy:
      replicas: 2
      restart_policy:
          condition: on-failure
          delay: "5s"
          max_attempts: 5
          window: "30s"

  programming-ui:
    build: 
      context: programming-ui
      dockerfile: Dockerfile.prod
    image: programming-ui-prod
    restart: "on-failure"
    ports:
      - 3000:80
    depends_on:
      - programming-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
      - programming-ui
    ports:
      - 7800:7800

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
    profiles:
      - e2e-testing